version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gen-excel-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - gen-excel-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gen-excel-backend
    environment:
      Jwt__Issuer: "GenExcel"
      Jwt__Audience: "GenExcel"
      Jwt__Key: "${JWT_KEY}"
      Jwt__ExpiresMinutes: "60"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: "Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True"
    depends_on:
      - sqlserver
    ports:
      - "${BACKEND_PORT}:8080"
    networks:
      - gen-excel-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gen-excel-frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - gen-excel-net

volumes:
  sql_data:

networks:
  gen-excel-net:
    driver: bridge
